version: '3'
services:
  api:
    container_name: api
    image: api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: PRODUCTION
      JWT_SECRET: secret
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
  
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro